management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,swagger-ui"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: "Api de transações"
    version: 1.0.0
    description: "Api responsável por gerenciar transações e estatísticas"


  metrics:
    tags:
      application: api-transacoes
    enable:
      all: true

springdoc:
  show-actuator: true